(defvar x-r-map (make-sparse-keymap)
  "Keymap for \"leader key\" shortcuts.")

(define-key x-r-map "@" 'point-to-register)
(define-key x-r-map "SPC" 'point-to-register)
(define-key x-r-map "+" 'increment-register)
(define-key x-r-map "M" 'bookmark-set-no-overwrite)
(define-key x-r-map "N" 'rectangle-number-lines)
(define-key x-r-map "b" 'bookmark-jump)
(define-key x-r-map "c" 'clear-rectangle)
(define-key x-r-map "d" 'delete-rectangle)
(define-key x-r-map "f" 'frameset-to-register)
(define-key x-r-map "g" 'insert-register)
(define-key x-r-map "i" 'insert-register)
(define-key x-r-map "j" 'jump-to-register)
(define-key x-r-map "k" 'kill-rectangle)
(define-key x-r-map "l" 'bookmark-bmenu-list)
(define-key x-r-map "m" 'bookmark-set)
(define-key x-r-map "n" 'number-to-register)
(define-key x-r-map "o" 'open-rectangle)
(define-key x-r-map "r" 'copy-rectangle-to-register)
(define-key x-r-map "s" 'copy-to-register)
(define-key x-r-map "t" 'string-rectangle)
(define-key x-r-map "w" 'window-configuration-to-register)

(defvar x-map (make-sparse-keymap)
  "Keymap for \"x key\" shortcuts.")

(define-key x-map "c" 'save-buffers-kill-terminal)

(define-key x-map "e" 'kmacro-end-and-call-macro)
(define-key x-map "l" 'count-lines-page)
(define-key x-map "o" 'marco-other-window)
(define-key x-map "s" 'delete-whitespace-and-save)
(define-key x-map " " 'rectangle-mark-mode)
(define-key x-map "5" 'ctl-x-5-prefix)
(define-key x-map "b" 'counsel-switch-buffer)
(define-key x-map "f" 'counsel-find-file)

(define-key x-map "(" 'start-kbd-macro)
(define-key x-map ")" 'end-kbd-macro)
(define-key x-map ";" 'comment-line)
(define-key x-map "-" 'text-scale-decrease)
(define-key x-map "=" 'text-scale-increase)
(define-key x-map "k" 'kill-current-buffer)
(define-key x-map "z" 'repeat)

(define-key x-map "0" 'delete-window)
(define-key x-map "1" 'delete-other-windows)
(define-key x-map "2" 'h-split-move)
(define-key x-map "3" 'v-split-move)

(define-key x-map "r" x-r-map)

(defvar g-map (make-sparse-keymap)
  "Keymap for \"g key\" shortcuts.")

(define-key g-map "a" 'counsel-ag)
(define-key g-map "p" 'previous-error)
(define-key g-map "n" 'next-error)
(define-key g-map "g" 'goto-line)

;; (define-key g-map "d" 'lsp-find-definition)
;; (define-key g-map "r" 'lsp-find-references)

(define-key marco-mode-map (kbd "c") c-map)
(define-key marco-mode-map (kbd "x") x-map)
(define-key marco-mode-map (kbd "g") g-map)
