(define-minor-mode resizer-mode
  "resizer-mode is a mode for resizing windows."
  ;; initial value
  :init-value nil
  :global t
  ;; indicator for mode line
  :lighter " resize-window"
  :group 'resizer-group
  ;; minor mode bindings
  :keymap '(
            ((kbd "a") . do-it-right)
            ((kbd "b") . shrink-window-horizontally)
            ((kbd "c") . do-it-right)
            ((kbd "d") . do-it-right)
            ((kbd "e") . do-it-right)
            ((kbd "f") . enlarge-window-horizontally)
            ((kbd "g") . disable-resizer-mode)
            ((kbd "h") . do-it-right)
            ((kbd "i") . do-it-right)
            ((kbd "j") . do-it-right)
            ((kbd "k") . do-it-right)
            ((kbd "l") . do-it-right)
            ((kbd "m") . do-it-right)
            ((kbd "n") . enlarge-window)
            ((kbd "o") . do-it-right)
            ((kbd "p") . shrink-window)
            ((kbd "q") . quoted-insert)
            ((kbd "r") . do-it-right)
            ((kbd "s") . do-it-right)

            ((kbd "t") . do-it-right)
            ((kbd "u") . do-it-right)
            ((kbd "v") . do-it-right)
            ((kbd "w") . do-it-right)
            ((kbd "x") . do-it-right)
            ((kbd "y") . do-it-right)
            ((kbd "z") . do-it-right)

            ((kbd " ") . do-it-right)

            ((kbd ";") . do-it-right)

            ((kbd "]") . do-it-right)
            ((kbd "[") . do-it-right)
            ((kbd "{") . do-it-right)
            ((kbd "}") . do-it-right)

            ((kbd "\\") . do-it-right)
            ((kbd "/") . do-it-right)

            ((kbd "<") . do-it-right)
            ((kbd ">") . do-it-right)
            ((kbd "'") . do-it-right)
            ((kbd "\"") . do-it-right)
            ((kbd ",") . do-it-right)
            ((kbd ".") . do-it-right)

            ((kbd ":") . do-it-right)
            ((kbd "(") . do-it-right)
            ((kbd ")") . do-it-right)
            ((kbd "?") . do-it-right)

            ((kbd "$") . do-it-right)
            ((kbd "!") . do-it-right)
            ((kbd "&") . do-it-right)
            ((kbd "%") . do-it-right)
            ((kbd "@") . do-it-right)
            ((kbd "#") . do-it-right)
            ((kbd "^") . do-it-right)
            ((kbd "*") . do-it-right)
            ((kbd "~") . do-it-right)

            ((kbd "0") . do-it-right)
            ((kbd "1") . do-it-right)
            ((kbd "2") . do-it-right)
            ((kbd "3") . do-it-right)
            ((kbd "4") . do-it-right)
            ((kbd "5") . do-it-right)
            ((kbd "6") . do-it-right)
            ((kbd "7") . do-it-right)
            ((kbd "8") . do-it-right)
            ((kbd "9") . do-it-right)

            ((kbd "-") . do-it-right)
            ((kbd "_") . do-it-right)
            ((kbd "+") . do-it-right)
            ((kbd "=") . do-it-right)

            ((kbd "A") . do-it-right)
            ((kbd "B") . do-it-right)
            ((kbd "C") . do-it-right)
            ((kbd "D") . do-it-right)
            ((kbd "E") . do-it-right)
            ((kbd "F") . do-it-right)
            ((kbd "G") . do-it-right)
            ((kbd "H") . do-it-right)
            ((kbd "I") . do-it-right)
            ((kbd "J") . do-it-right)
            ((kbd "K") . do-it-right)
            ((kbd "L") . do-it-right)
            ((kbd "M") . do-it-right)
            ((kbd "N") . do-it-right)
            ((kbd "O") . do-it-right)
            ((kbd "P") . do-it-right)
            ((kbd "Q") . do-it-right)
            ((kbd "R") . do-it-right)
            ((kbd "S") . do-it-right)
            ((kbd "T") . do-it-right)
            ((kbd "U") . do-it-right)
            ((kbd "V") . do-it-right)
            ((kbd "W") . do-it-right)
            ((kbd "X") . do-it-right)
            ((kbd "Y") . do-it-right)
            ((kbd "Z") . do-it-right)))
