(global-set-key (kbd "C-c e") 'counsel-M-x)
(global-set-key (kbd "C-s") 'swiper-isearch)
(global-set-key (kbd "C-c i") 'counsel-imenu)
;; (global-set-key (kbd "C-c i") 'idomenu)
;; (global-set-key (kbd "C-c e") 'smex)
(global-set-key (kbd "C-x C-s") 'delete-whitespace-and-save)
(global-set-key (kbd "C-c a") 'avy-goto-char)
(global-set-key (kbd "C-;") 'comment-line)
(global-set-key (kbd "C-x k") 'kill-current-buffer)
(global-set-key (kbd "C-c c") 'projectile-compile-project)
(global-set-key (kbd "C-c r") 'projectile-run-project)
(global-set-key (kbd "C-c n") 'next-buffer)
(global-set-key (kbd "C-c p") 'previous-buffer)
(global-set-key (kbd "C-c f") 'projectile-find-file)
(global-set-key (kbd "C-c t") 'term-split)
;; (global-set-key (kbd "C-s") 'ioccur)
;; (global-set-key (kbd "C-c s") 'counsel-projectile-ag)

(setq search-whitespace-regexp ".*?")

(global-set-key (kbd "C-z") 'do-it-right)

(global-set-key (kbd "C-x 2") 'horizontal-split-move)
(global-set-key (kbd "C-x 3") 'vertical-split-move)

(global-set-key (kbd "C-c g n") 'next-error)
(global-set-key (kbd "C-c g p") 'previous-error)
(global-set-key (kbd "C-c g d") 'lsp-find-definition)
(global-set-key (kbd "C-c g r") 'lsp-find-references)
(global-set-key (kbd "C-c g a") 'counsel-ag)
(global-set-key (kbd "C-c g g") 'lsp-ivy-workspace-symbol)
